(deftheme cipher
  "Created 2018-04-27.")

(custom-theme-set-faces
 'cipher
 '(cursor ((t (:background "#0a0a0a" :foreground "#fafafa"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "#8e7000" :weight bold))))
 '(minibuffer-prompt ((t (:foreground "#3f823c" :weight bold))))
 '(highlight ((t (:background "#7033a0" :foreground "#f3f1f5"))))
 '(region ((t (:background "#0a0a0a" :foreground "#fafafa"))))
 '(shadow ((t (:foreground "#36508a"))))
 '(secondary-selection ((t (:background "#991e54" :foreground "#f3f1f5"))))
 '(trailing-whitespace ((t (:background "#B00000" :foreground "#ffffff"))))
 '(font-lock-builtin-face ((t (:foreground "#3f823c"))))
 '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face))))
 '(font-lock-comment-face ((t (:foreground "#30385a" :slant italic))))
 '(font-lock-constant-face ((t (:foreground "#0062d0"))))
 '(font-lock-doc-face ((t (:foreground "#1a707d"))))
 '(font-lock-function-name-face ((t (:foreground "#1a753d" :weight bold))))
 '(font-lock-keyword-face ((t (:foreground "#0062d0" :weight bold))))
 '(font-lock-negation-char-face ((t (:background "#fafce6" :foreground "#ba571c" :weight bold))))
 '(font-lock-preprocessor-face ((t (:foreground "#ba571c"))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#1a707d" :weight bold))))
 '(font-lock-regexp-grouping-construct ((t (:weight bold))))
 '(font-lock-string-face ((t (:foreground "#1c77c2"))))
 '(font-lock-type-face ((t (:foreground "#307c99" :weight bold))))
 '(font-lock-variable-name-face ((t (:foreground "#b4508c" :weight bold))))
 '(font-lock-warning-face ((t (:background "#fafce6" :foreground "#cc1300" :weight bold))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:foreground "#0062d0" :underline t))))
 '(link-visited ((t (:inherit link :foreground "#991e54"))))
 '(fringe ((t (:background "#fafafa" :height 1.5))))
 '(header-line ((t (:inherit mode-line))))
 '(tooltip ((t (:inherit variable-pitch :background "#634e2f" :foreground "#f3f1f5"))))
 '(mode-line ((t (:background "#43474a" :foreground "#f3f1f5" :box (:line-width 1 :style released-button)))))
 '(mode-line-buffer-id ((t (:foreground "#fafafa" :weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((t (:background "#33373a" :foreground "#d4c84d" :slant italic))))
 '(mode-line-inactive ((t (:background "#533e1f" :foreground "#e3e1e5" :box (:line-width 1 :color "gray40")))))
 '(isearch ((t (:background "#1a707d" :foreground "#fafafa"))))
 '(isearch-fail ((t (:background "#cc1300" :foreground "#fafce6" :weight bold))))
 '(lazy-highlight ((t (:background "#3f823c" :foreground "#fafafa" :underline t))))
 '(match ((t (:background "#307c99" :foreground "#fafafa" :weight bold))))
 '(next-error ((t (:background "#ba571c" :foreground "#fafafa" :weight bold))))
 '(query-replace ((t (:background "#b4508c" :foreground "#fafafa" :weight bold))))
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#33373a" :inherit rainbow-delimiters-base-face))))
 '(rainbow-delimiters-depth-2-face ((t (:inherit rainbow-delimiters-base-face :foreground "#30385a"))))
 '(rainbow-delimiters-depth-3-face ((t (:inherit rainbow-delimiters-base-face :foreground "#1a753d"))))
 '(rainbow-delimiters-depth-4-face ((t (:inherit rainbow-delimiters-base-face :foreground "#945800"))))
 '(rainbow-delimiters-depth-5-face ((t (:inherit rainbow-delimiters-base-face :foreground "#a2447d"))))
 '(rainbow-delimiters-depth-6-face ((t (:inherit rainbow-delimiters-base-face :foreground "#0062d0"))))
 '(rainbow-delimiters-depth-7-face ((t (:inherit rainbow-delimiters-base-face :foreground "#3f823c"))))
 '(rainbow-delimiters-depth-8-face ((t (:inherit rainbow-delimiters-base-face :foreground "#8e7000"))))
 '(rainbow-delimiters-depth-9-face ((t (:inherit rainbow-delimiters-base-face :foreground "#b4508c"))))
 '(rainbow-delimiters-base-face ((default (:inherit nil))))
 '(outline-1 ((t (:foreground "#634e2f" :weight bold :height 1.5))))
 '(outline-2 ((t (:foreground "#991e54" :weight bold :height 1.4))))
 '(outline-3 ((t (:foreground "#0a0a0a" :weight bold :height 1.3))))
 '(outline-4 ((t (:foreground "#43474a" :weight bold :height 1.2))))
 '(outline-5 ((t (:foreground "#634e2f" :weight bold :height 1.1))))
 '(outline-6 ((t (:foreground "#1a753d" :weight bold))))
 '(outline-7 ((t (:foreground "#0062d0" :weight bold))))
 '(outline-8 ((t (:foreground "#1a707d" :weight bold))))
 '(git-gutter:added ((t (:background "#1a753d" :foreground "#fafafa" :weight normal))))
 '(git-gutter:deleted ((t (:background "#cc1300" :foreground "#fafafa" :weight normal))))
 '(git-gutter:unchanged ((t (:background "#945800" :foreground "#fafafa" :weight normal))))
 '(git-gutter:modified ((t (:background "#a2447d" :foreground "#fafafa" :weight normal))))
 '(git-gutter:separator ((t (:background "#1a707d" :foreground "#fafafa" :weight normal))))
 '(org-todo ((t (:background "#b4508c" :foreground "#fafafa" :weight bold))))
 '(org-done ((t (:background "#307c99" :foreground "#fafafa" :weight bold))))
 '(org-document-info ((t (:foreground "#43474a" :weight bold))))
 '(org-document-info-keyword ((t (:background "#f3f1f5" :foreground "#7033a0" :weight bold))))
 '(org-meta-line ((t (:foreground "#0a0a0a" :slant italic :weight bold))))
 '(org-document-title ((t (:foreground "#36508a" :weight bold))))
 '(flycheck-error ((t (:background "#cc1300" :foreground "#fafafa" :slant italic :weight bold))))
 '(flycheck-fringe-warning ((t (:inherit (warning)))))
 '(flycheck-fringe-info ((t (:inherit (success)))))
 '(success ((t (:foreground "#1a753d" :weight bold))))
 '(flycheck-fringe-error ((t (:inherit (error)))))
 '(flycheck-error-list-error ((t (:inherit (error)))))
 '(flycheck-error-list-warning ((t (:inherit (warning)))))
 '(flycheck-error-list-checker-name ((t (:inherit (font-lock-function-name-face)))))
 '(flycheck-error-list-line-number ((t (:inherit (font-lock-constant-face)))))
 '(flycheck-error-list-info ((t (:inherit (success)))))
 '(flycheck-error-list-highlight ((t (:inherit (highlight)))))
 '(flycheck-error-list-id-with-explainer ((t (:box (:line-width 1 :color nil :style released-button) :inherit (flycheck-error-list-id)))))
 '(flycheck-error-list-column-number ((t (:inherit (font-lock-constant-face)))))
 '(flycheck-error-list-id ((t (:inherit (font-lock-type-face)))))
 '(flycheck-error-list-filename ((t (:inherit (font-lock-variable-name-face)))))
 '(show-paren-match ((t (:background "#307c99" :foreground "#fafafa" :weight bold))))
 '(warning ((t (:foreground "#ba571c" :weight bold))))
 '(default ((t (:inherit nil :stipple nil :background "#fafafa" :foreground "#0a0a0a" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 105 :width normal :foundry "SRC" :family "Hack"))))
 '(mc/cursor-face ((t (:background "#634e2f" :foreground "#fafafa")))))

(provide-theme 'cipher)
