#! /bin/sh

# Visual options
# ==============================================================================

# workspaces
# ------------------------------------------------------------------------------
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# window rules
# ------------------------------------------------------------------------------
bspc config border_width 2
bspc config window_gap 5

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true
bspc config focus_follows_pointer false
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config click_to_focus true
bspc config auto_alternate true
bspc config auto_cancel true
# bspc config initial_polarity second_child

# program-specific rules
bspc rule -a Emacs state=tiled

# colours
# ------------------------------------------------------------------------------

# define scheme
source "$HOME/.my_Xcolors/active-tempus-theme.sh"

# window decorations
bspc config normal_border_color "$background"
bspc config active_border_color "$color8"
bspc config focused_border_color "$color10"
bspc config presel_feedback_color "$color13"

# autostart
# ==============================================================================

sxhkd &
xrdb -merge $HOME/.Xresources
. $HOME/.config/polybar/launch.sh

# start URxvt server
if [ -x /usr/bin/urxvtd ]; then
	urxvtd --quiet --opendisplay --fork &
fi

# start music server
if [ -x /usr/bin/mpd ]; then
	mpd
fi

# manage wallpaper
if [ -x /usr/bin/feh ]; then
    feh --bg-fill ~/.wallpaper.jpg
fi

# display compositor
if [ -x /usr/bin/compton ]; then
    compton -b &
fi

# display temperature regulator
if [ -x /usr/bin/redshift ]; then
    redshift -c ~/.config/redshift.conf &
fi

# specify keyboard layouts and compose key
if [ -x /usr/bin/setxkbmap ]; then
    setxkbmap -option compose:menu
    setxkbmap -layout 'us,gr' -option 'grp:alt_caps_toggle'
fi

# hardware enablement tool
if [ -x /usr/bin/xinput ]; then
    # `xinput list` devices
    # `xinput list-props` device properties

    # syntax is [id] [prop] [boolean]
    # enable touchpad tap to click
    # xinput set-prop 11 275 1
    xinput set-prop 11 277 1
fi

# hide mouse pointer
if [ -x /usr/bin/unclutter ]; then
    unclutter &
fi
