#! /bin/sh

# autostart
# ==============================================================================
# NOTE sxhkd and polybar are core parts of [my] bspwm
# the rest are loaded only if they are in the PATH

sxhkd &
. $HOME/.config/polybar/launch.sh &

if [ -x /usr/bin/feh ]; then
    feh --bg-fill ~/.wallpaper.jpg
fi

if [ -x /usr/bin/compton ]; then
    compton -b &
fi

if [ -x /usr/bin/dunst ]; then
    dunst &
fi

if [ -x /usr/bin/redshift ]; then
    redshift -c ~/.config/redshift.conf &
fi

if [ -x /usr/bin/unclutter ]; then
    unclutter &
fi


if [ -x /usr/bin/xinput ]; then
    # `xinput list` devices
    # `xinput list-props` device properties

    # syntax is [id] [prop] [boolean]
    # enable touchpad tap to click
    xinput set-prop 11 277 1
fi

# Visual options
# ==============================================================================

# workspaces
# ------------------------------------------------------------------------------
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# window rules
# ------------------------------------------------------------------------------
bspc config border_width 2
bspc config window_gap 5

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true
bspc config focus_follows_pointer false
bspc config click_to_focus true
bspc config auto_alternate true
bspc config auto_cancel true
# bspc config initial_polarity second_child

# colours
# ------------------------------------------------------------------------------

# define scheme
# tempus_warp (by Protesilaos Stavrou)
# https://github.com/protesilaos/tempus-themes
tempus_color0=#141a19
tempus_color1=#ff1414
tempus_color2=#009600
tempus_color3=#928100
tempus_color4=#4f76ff
tempus_color5=#dd38bc
tempus_color6=#358aaa
tempus_color7=#927B80
tempus_color8=#201428
tempus_color9=#ff5500
tempus_color10=#3aa43a
tempus_color11=#b38a00
tempus_color12=#8082ff
tempus_color13=#d159fd
tempus_color14=#1da190
tempus_color15=#928f90

# window decorations
bspc config normal_border_color "$tempus_color0"
bspc config active_border_color "$tempus_color8"
bspc config focused_border_color "$tempus_color10"
bspc config presel_feedback_color "$tempus_color13"
bspc config urgent_border_color "$tempus_color1"
