#! /bin/sh

# autostart
sxhkd &
. $HOME/.config/polybar/launch.sh &
feh --bg-fill ~/.wallpaper.jpg
compton -b &

# workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Visual options
bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer false
bspc config auto_alternate true
bspc config auto_cancel true

bspc config normal_border_color "#141a19"
bspc config active_border_color "#201428"
bspc config focused_border_color "#3aa43a"
bspc config presel_feedback_color "#dd38bc"
bspc config urgent_border_color "#ff5500"
